export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const ALL_ADMIN_PRODUCT_REQUEST = "ALL_ADMIN_PRODUCT_REQUEST";
export const ALL_ADMIN_PRODUCT_SUCCESS = "ALL_ADMIN_PRODUCT_SUCCESS";
export const ALL_ADMIN_PRODUCT_FAIL = "ALL_ADMIN_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const TOP_PRODUCTS_REQUEST = "TOP_PRODUCTS_REQUEST";
export const TOP_PRODUCTS_SUCCESS = "TOP_PRODUCTS_SUCCESS";
export const TOP_PRODUCTS_FAIL = "TOP_PRODUCTS_FAIL";

export const NEW_ARRIVALS_REQUEST = "NEW_ARRIVALS_REQUEST";
export const NEW_ARRIVALS_SUCCESS = "NEW_ARRIVALS_SUCCESS";
export const NEW_ARRIVALS_FAIL = "NEW_ARRIVALS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";